version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/app
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - mongo
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"