version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "python init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"]
    environment:
      DATABASE_URL: postgresql://user:password@db/my_service
      MONGODB_URL: mongodb://root:example@mongo:27017
    depends_on:
      - db
      - mongo
    ports:
      - "8000:8000"
    networks:
      - app-network

volumes:
  postgres_data:
  mongo_data:

networks:
  app-network:
