# Generated by Django 5.1.5 on 2025-01-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('to_do', 'В работу'), ('in_progress', 'В работе'), ('done', 'Выполнен'), ('cancelled', 'Отменен')], default='to_do', max_length=15)),
                ('estimated_hours', models.FloatField(blank=True, null=True, verbose_name='Оценка в часах')),
                ('attachment', models.TextField(blank=True, null=True, verbose_name='Текстовое вложение')),
            ],
        ),
    ]
